// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5WvEbAyKE0fwtJRE9f0tUc1C6xnRf7gs',
    appId: '1:609577257326:web:f69f8d3917052d073d597f',
    messagingSenderId: '609577257326',
    projectId: 'booktopia-cc96f',
    authDomain: 'booktopia-cc96f.firebaseapp.com',
    storageBucket: 'booktopia-cc96f.appspot.com',
    measurementId: 'G-W2D76D79P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwM9vR43QD7LwEJRmylKHzFKL6f0vrITc',
    appId: '1:609577257326:android:8d0df288afcd549e3d597f',
    messagingSenderId: '609577257326',
    projectId: 'booktopia-cc96f',
    storageBucket: 'booktopia-cc96f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEBD9mC13YVhLXhkgUvwepyBudJNFTo0c',
    appId: '1:609577257326:ios:964c970f8f60e9e33d597f',
    messagingSenderId: '609577257326',
    projectId: 'booktopia-cc96f',
    storageBucket: 'booktopia-cc96f.appspot.com',
    iosClientId: '609577257326-httndt0s2fpa435eqead7u03dsn78gn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectBooktopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEBD9mC13YVhLXhkgUvwepyBudJNFTo0c',
    appId: '1:609577257326:ios:96eda6f839ba0ead3d597f',
    messagingSenderId: '609577257326',
    projectId: 'booktopia-cc96f',
    storageBucket: 'booktopia-cc96f.appspot.com',
    iosClientId: '609577257326-3odqtgbdjcg0at7sivtllnf4vclpq9do.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectBooktopia.RunnerTests',
  );
}
